# Overrides values
hostname: bigbang.dev
flux:
  interval: 1m
  rollback:
    cleanupOnFail: false
gatekeeper:
  values:
    replicas: 1
istio:
  values:
    kiali:
      dashboard:
        auth:
          strategy: anonymous
logging:
  values:
    elasticsearch:
      data:
        count: 1
        persistence:
          size: 512Mi
        resources:
          limits:
            cpu: 1
            memory: 512Mi
      master:
        count: 1
        persistence:
          size: 512Mi
        resources:
          limits:
            cpu: 1
            memory: 512Mi
monitoring:
  enabled: false
twistlock:
  enabled: false
  values:
    console:
      persistence:
        size: 1Gi