hostname: bigbang.dev

# Toggle sourcing from external repos
# TODO: All this does right now is toggle GitRepositories, it is _not_ fully functional
offline: false

# Registry credentials to use from pulling images from private registry, will create an appropriate imagePullSecret in all relevant namespaces
registryCredentials:
  registry: registry1.dsop.io
  username: ""
  password: ""
  email: ""

# Flux reconciliation parameters
flux:
  interval: 2m
  install:
    retries: 3
  upgrade:
    retries: 3
  rollback:
    timeout: 5m
    cleanupOnFail: true

#package:
#  enabled: true
#  git:
#    repo: ""
#    branch: ""
#    commit: ""
#    tag: ""
#  values: {}

# ----------------------------------------------------------------------------------------------------------------------
# Istio
#
istio:
  enabled: true
  git:
    repo: https://repo1.dsop.io/platform-one/big-bang/apps/core/istio-controlplane.git
    path: "./chart"
  values: {}

istiooperator:
  git:
    repo: https://repo1.dsop.io/platform-one/big-bang/apps/core/istio-operator.git
    path: "./chart"
  values: {}
# ----------------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------------------------------------
# Cluster Auditor
#
clusterAuditor:
  enabled: true
  git: 
    repo: https://repo1.dsop.io/platform-one/big-bang/apps/core/cluster-auditor.git
    path: "./charts"
    branch: chart-release
  values: {}
# ----------------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------------------------------------
# OPA Gatekeeper
#
gatekeeper:
  enabled: true
  git:
    repo: https://repo1.dsop.io/platform-one/big-bang/apps/core/policy.git
    path: "./chart"
  values: {}
# ----------------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------------------------------------
# Logging
#
logging:
  enabled: true
  git:
    repo: https://repo1.dsop.io/platform-one/big-bang/apps/core/elasticsearch-kibana.git
    path: "./chart"
  values: {}

eckoperator:
  git:
    repo: https://repo1.dsop.io/platform-one/big-bang/apps/core/eck-operator.git
    path: "./chart"
  values: {}

fluentbit:
  git:
    repo: https://repo1.dsop.io/platform-one/big-bang/apps/core/fluentbit.git
    path: "./chart"
  values: {}
# ----------------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------------------------------------
# Monitoring
#
monitoring:
  enabled: true
  git:
    repo: https://repo1.dsop.io/platform-one/big-bang/apps/core/monitoring.git
    path: "./chart"
    branch: release-v0.2.x
#    commit: ""
#    tag: ""
  values: {}
# ----------------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------------------------------------
# Twistlock
#
twistlock:
  enabled: true
  git:
    repo: https://repo1.dsop.io/platform-one/big-bang/apps/security-tools/twistlock.git
    path: "./chart"
    branch: chart-release
#    commit: ""
#    tag: ""
  values: {}
# ----------------------------------------------------------------------------------------------------------------------

addons:
  argocd:
    enabled: false
    git:
      repo: https://repo1.dsop.io/platform-one/big-bang/apps/core/argocd.git
      path: "./chart"
      branch: chart-release
    values: {}
