{{- if .Values.istiooperator.enabled }}
{{- $name := include "bigbang.tagname" (merge .Values.istiooperator (dict "name" "istio-operator")) }}
{{- $fluxSettingsIstioOperator := merge .Values.istiooperator.flux .Values.flux -}}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: istio-operator
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: istio-operator
  chart:
    spec:
      chart: {{ .Values.istiooperator.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: {{ $name }}
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsIstioOperator | nindent 2 }}

  {{- if .Values.istiooperator.postRenderers }}
  postRenderers:
  {{ toYaml .Values.istiooperator.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-{{ $name }}-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-{{ $name }}-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-{{ $name }}-values
      kind: Secret
      valuesKey: "overlays"

  {{- if .Values.gatekeeper.enabled }}
  dependsOn:
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}