---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: istio-operator
    app.kubernetes.io/component: "core"
  name: kube-api-server
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: istio-operator
          app.kubernetes.io/component: "core"
    ports:
    - port: 443
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: istio-operator
    app.kubernetes.io/component: "core"
  name: dns-lookups
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 53
      protocol: UDP
  podSelector: {}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: istio-operator
    app.kubernetes.io/component: "core"
  name: istio-operator-metrics
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
    ports:
    - port: 8383
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: istio-operator
      app.kubernetes.io/component: "core"
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: istio-operator
    app.kubernetes.io/component: "core"
  name: deny-ingress
  namespace: flux-system
spec:
  egress:
  - {}
  ingress:
  - from:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---