{{- if .Values.istiooperator.enabled }}
{{- $name := include "bigbang.tagname" (merge .Values.istiooperator (dict "name" "istio-operator")) }}
{{- include "values-secret" (dict "root" $ "package" .Values.istiooperator "name" $name "defaults" (include "bigbang.defaults.istiooperator" .)) }}
{{- end }}

{{- define "bigbang.defaults.istiooperator" -}}
createNamespace: false

imagePullSecrets:
  - private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

revision: {{ include "bigbang.tag" .Values.istio }}
{{- end -}}
