{{- if .Values.kiali.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: kiali
  labels:
    {{- if .Values.istio.enabled }}{{- include "bigbang.istioInjectionLabel" .  | nindent 4 }}{{- end }}
    app.kubernetes.io/name: kiali
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}