{{- if and  .Values.kiali.enabled .Values.kiali.sso.enabled .Values.sso.certificate_authority }}
apiVersion: v1
kind: Secret
metadata:
  name: tls-ca-sso
  namespace: kiali
type: Opaque
data:
  ca.pem: {{ .Values.sso.certificate_authority | b64enc }}
{{- end }}