{{- if .Values.kiali.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.kiali "name" "kiali" "defaults" (include "bigbang.defaults.kiali" .)) }}
{{- end }}

{{- define "bigbang.defaults.kiali" -}}
hostname: {{ .Values.hostname }}
istio:
  enabled: {{ .Values.istio.enabled }}
monitoring:
  enabled: {{ .Values.monitoring.enabled }}
elasticsearch:
  enabled: {{ .Values.logging.enabled }}
{{- if .Values.kiali.sso.enabled }}
cr:
  spec:
    pod_labels:
      protect: keycloak
{{- end }}
{{- end -}}