{{- if and (not .Values.offline) .Values.gatekeeper.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gatekeeper
  namespace: {{ .Release.Namespace }}
spec:
  ignore: |
    # exclude file extensions
    /**/*.md
    /**/*.txt
    /**/*.sh
  interval: {{ .Values.flux.interval }}
  ref:
    branch: {{ .Values.gatekeeper.git.branch }}
  url: {{ .Values.gatekeeper.git.repo }}
{{- end }}
