{{- if and (not .Values.offline) (or .Values.gatekeeper.enabled .Values.clusterAuditor.enabled) }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gatekeeper
  namespace: {{ .Release.Namespace }}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.gatekeeper.git.repo }}
  ref:
    tag: "3.1.2-bb.0"
  {{ include "gitIgnore" . }}
{{- end }}
