{{- if or .Values.gatekeeper.enabled .Values.clusterAuditor.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    gatekeeper.sh/system: "yes"
    app.kubernetes.io/name: gatekeeper
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
  name: gatekeeper-system
{{- end }}