{{- if or .Values.gatekeeper.enabled .Values.clusterAuditor.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.gatekeeper "name" "gatekeeper" "defaults" (include "bigbang.defaults.gatekeeper" .)) }}
{{- end }}

{{- define "bigbang.defaults.gatekeeper" -}}
image:
  pullSecrets:
  - name: private-registry
postInstall:
  labelNamespace:
    enabled: false
    image:
      pullSecrets:
      - name: private-registry
networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}
violations:  # Try to keep this in alpha order to make it easier to find keys
  {{- if .Values.monitoring.enabled }}
  hostNetworking:
    match:
      excludedNamespaces:
        - monitoring # Allow node exporter to export metrics. The exporters live in pod monitoring-monitoring-prometheus-node-exporter-XXXX
  {{- end }}

  {{- if .Values.logging.enabled }}
  noPrivilegedContainers:
    match:
      excludedNamespaces:
        - kube-system
        - logging # Fluentbit needs privileged to read and store the buffer for tailing logs from the nodes
  {{- end }}

  {{- if .Values.monitoring.enabled }}
  restrictedTaint:
    match:
      excludedNamespaces:
        - kube-system
        - monitoring # Prometheus Node Exporter needs to be able to run on all nodes, regardless of taint, to gather node metrics
  {{- end }}

  {{- if .Values.logging.enabled }}
  selinuxPolicy:
    match:
      excludedNamespaces:
        - logging # FluentBit needs selinux option type spc_t
  {{- end }}
  allowedDockerRegistries:
    match:
      excludedNamespaces: 
       {{- if .Values.istio.enabled }}
        - istio-system # allows creation for loadbalancer pods for various ports and various vendor loadbalancers
       {{- end }}
        - kube-system # ignored as the kubernetes distro cannot be controlled
    {{- if .Values.addons.mattermost.enabled }}
    parameters:
      exemptContainers:
        - init-check-database # mattermost needs postgres:13 image and cannot override the upstream
    {{- end }}
{{- end -}}
