{{- if or .Values.gatekeeper.enabled .Values.clusterAuditor.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.gatekeeper "name" "gatekeeper" "defaults" (include "bigbang.defaults.gatekeeper" .)) }}
{{- end }}

{{- define "bigbang.defaults.gatekeeper" -}}
image:
  pullSecrets:
  - name: private-registry
violations:
  httpsOnly:
    match:
      excludedNamespaces: 
       {{- if .Values.addons.mattermost.enabled }}
        # mattermost currently does not useIngressTLS hence Ingress is created without TLS field by the operator.
        # Adding exemption, pending https://github.com/mattermost/mattermost-operator/issues/235
        - mattermost
       {{- end }}
postInstall:
  labelNamespace:
    enabled: false
    image:
      pullSecrets:
      - name: private-registry
networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}        
{{- end -}}
