{{- if or .Values.gatekeeper.enabled .Values.clusterAuditor.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.gatekeeper "name" "gatekeeper" "defaults" (include "bigbang.defaults.gatekeeper" .)) }}
{{- end }}

{{- define "bigbang.defaults.gatekeeper" -}}
image:
  pullSecrets:
  - name: private-registry
postInstall:
  labelNamespace:
    enabled: false
    image:
      pullSecrets:
      - name: private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}
violations:  # Try to keep this in alpha order to make it easier to find keys

  {{- if .Values.addons.mattermost.enabled }}
  allowedDockerRegistries:
    parameters:
      exemptContainers:
        - init-check-database # mattermost needs postgres:13 image and cannot override the upstream
  {{- end }}

  {{- if .Values.monitoring.enabled}}
  allowedHostFilesystem:
    match:
      excludedNamespaces: 
        # required for monitoring's prometheus-node-exporter to get node metrics
        - monitoring
  {{- end }}

  {{- if .Values.addons.mattermost.enabled }}
  httpsOnly:
    match:
      excludedNamespaces:
        # mattermost currently does not useIngressTLS hence Ingress is created without TLS field by the operator.
        # Adding exemption, pending https://github.com/mattermost/mattermost-operator/issues/235
        - mattermost
  {{- end }}

  {{- if .Values.logging.enabled }}
  noPrivilegedContainers:
    match:
      excludedNamespaces:
        - logging # Fluentbit needs privileged to read and store the buffer for tailing logs from the nodes
  {{- end }}

  {{- if .Values.monitoring.enabled }}
  restrictedTaint:
    match:
      excludedNamespaces:
        - monitoring # Prometheus Node Exporter needs to be able to run on all nodes, regardless of taint, to gather node metrics
  {{- end }}

  {{- if .Values.logging.enabled }}
  selinuxPolicy:
    match:
      excludedNamespaces:
        - logging # FluentBit needs selinux option type spc_t
  {{- end }}

  {{- if or .Values.fluentbit.enabled (or .Values.twistlock.enabled .Values.monitoring.enabled) }}
  volumeTypes:
    match:
      excludedNamespaces:
       {{- if .Values.fluentbit.enabled }}
        # fluent-bit container requires certain host level access to ship logs and for keep track of state
        # https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#workflow-of-tail-kubernetes-filter
        - logging
       {{- end }}
       {{- if .Values.twistlock.enabled }}
        # Twistlock requires /dev/log for its syslog daemon.
        # https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/audit/logging.html#
        - twistlock
       {{- end }}
       {{- if .Values.monitoring.enabled }}
        # Prometheus node exported requires hostpath hardcoded in upstream chart on which monitoring pkg has a direct dependency
        # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/templates/daemonset.yaml#L150
        - monitoring
       {{- end }}
  {{- end }}
{{- end -}}
