{{- if or .Values.gatekeeper.enabled .Values.clusterAuditor.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.gatekeeper "name" "gatekeeper" "defaults" (include "bigbang.defaults.gatekeeper" .)) }}
{{- end }}

{{- define "bigbang.defaults.gatekeeper" -}}
image:
  pullSecrets:
  - name: private-registry
postInstall:
  labelNamespace:
    enabled: false
    image:
      pullSecrets:
      - name: private-registry
violations:
  allowedDockerRegistries:
    match:
      excludedNamespaces: 
        - istio-system # allows creation for loadbalancer pods for various ports and various vendor loadbalancers
        - kube-system # ignored as the kubernetes distro cannot be controlled
    parameters:
      exemptContainers:
        {{- if .Values.addons.mattermost.enabled}}
        - init-check-database # mattermost needs postgres:13 image and cannot override the upstream
        {{- else -}}
        []
        {{- end}}
networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}        
{{- end -}}
