{{- if .Values.twistlock.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: twistlock
  labels:
    app.kubernetes.io/name: twistlock
    app.kubernetes.io/component: "security"
    {{- include "commonLabels" . | nindent 4}}
    {{- if .Values.istio.enabled }}{{- include "bigbang.istioInjectionLabel" .  | nindent 4 }}{{- end }}
{{- end }}