{{- if and  .Values.twistlock.enabled .Values.twistlock.sso.enabled .Values.sso.certificate_authority}}
apiVersion: v1
kind: Secret
metadata:
  name: tls-ca-sso
  namespace: twistlock
type: Opaque
data:
  ca.pem: {{ .Values.sso.certificate_authority | b64enc }}
{{- end }}