{{- if and (or .Values.twistlock.enabled ) .Values.twistlock.sso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tls-ca-sso
  namespace: twistlock
type: Opaque
data:
  ca.pem: {{ .Values.sso.certificate_authority | b64enc }}
{{- end }}