{{- if and  .Values.twistlock.enabled .Values.twistlock.sso.enabled .Values.sso.certificate_authority .Values.sso.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sso.secretName }}
  namespace: twistlock
type: Opaque
data:
  ca.pem: {{ .Values.sso.certificate_authority | b64enc }}
{{- end }}