{{- if .Values.twistlock.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.twistlock "name" "twistlock" "defaults" (include "bigbang.defaults.twistlock" .)) }}
{{- end }}

{{- define "bigbang.defaults.twistlock" -}}
hostname: {{ .Values.hostname }}

prometheus:
  servicemonitor:
    enabled: {{ .Values.monitoring.enabled }}

imagePullSecrets:
- name: private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  ingressLabels:
    {{- $gateway := (default "public" .Values.twistlock.ingress.gateway) }}
    app: {{ (get .Values.istio.gateways $gateway).ingressGateway }}
    istio: null

istio:
  enabled: {{ .Values.istio.enabled }}
  console:
    gateways:
    - istio-system/{{ default "public" .Values.twistlock.ingress.gateway }}

{{- end -}}
