{{- if .Values.twistlock.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.twistlock "name" "twistlock" "defaults" (include "bigbang.defaults.twistlock" .)) }}
{{- end }}

{{- define "bigbang.defaults.twistlock" -}}
hostname: {{ .Values.hostname }}

prometheus:
  servicemonitor:
    enabled: {{ .Values.monitoring.enabled }}

imagePullSecrets:
- name: private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}

istio:
  enabled: {{ .Values.istio.enabled }}
  console:
    hosts:
      - twistlock{{ if .Values.addons.keycloak.enabled }}.admin{{ end }}.{{ .Values.hostname }}
{{- end -}}
