{{- if and (not .Values.offline) .Values.addons.postgresoperator.enabled }}
{{ $name := "postgres-operator" }}
{{ $component := "package-utilities" }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/component: {{ $component }}
    {{- include "commonLabels" . | nindent 4}}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.addons.postgresoperator.git.repo }}
  ref:
    {{- include "validRef" .Values.addons.postgresoperator.git | nindent 4 }}
  {{ include "gitIgnore" . }}
  {{- include "gitCreds" . | nindent 2 }}
{{- end }}