{{- if .Values.addons.postgresoperator.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
  labels:
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/component: "application-utilities"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}