{{- if .Values.addons.postgresoperator.enabled }}
{{- if ( include "imagePullSecret" . ) }}
{{ $name := "postgres-operator" }}
{{ $component := "package-utilities" }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/component: {{ $component }}
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}