{{- if .Values.addons.postgresoperator.enabled }}
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: postgres-operator
  labels:
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/component: "application-utilities"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}