{{- if .Values.addons.sonarqube.enabled }}
{{- /* Default to istio being turned on, but disable if user sets istio to disable in the custom passthrough values.
We have to do it this way because ownership of "istio.enabled" is owned by the chart but also BigBang.  Sourcing values from the passthrough values also means
  we get to simplify the api space of BigBang just a little bit more.
*/ -}}
{{- $istio := .Values.addons.sonarqube.values.istio | default dict }}
{{- $istioInjection := "enabled" }}
{{- if and (hasKey $istio "enabled") (not $istio.enabled) }}
{{- $istioInjection = "disabled" }}
{{- end }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: {{ $istioInjection }}
  name: sonarqube
{{- end }}
