{{- if and (or .Values.addons.sonarqube.enabled ) .Values.addons.sonarqube.sso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tls-ca-sso
  namespace: sonarqube
type: Opaque
data:
  ca.pem: {{ .Values.sso.certificate_authority | b64enc }}
{{- end }}