apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: this
  namespace: flux-system
spec:
  ignore: |
    # exclude file extensions
    /**/*.md
    /**/*.txt
  interval: 1m
  ref:
    branch: $branch
  url: $repo
