stages:
  - package tests

package tests:
  stage: package tests
  tags:
    - bigbang
    - privileged
    - public
  image: registry.dsop.io/platform-one/private/big-bang/pipeline-templates/k3d-builder:b0b45793
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  before_script:
    # Starting dnsmasq for cluster dns resolution
    - docker run -d -p 53:53/udp -p 53:53 janeczku/go-dnsmasq:release-1.0.7
    - echo "nameserver 127.0.0.1" >> /etc/resolv.conf

    # Standup cluster
    - k3d cluster create umbrella  --k3s-server-arg "--disable=traefik" --k3s-server-arg "--disable=metrics-server" -p 80:80@loadbalancer -p 443:443@loadbalancer --wait --agents 1 --servers 1
    - while ! (kubectl get node | grep "agent" > /dev/null); do sleep 3; done
    - kubectl get nodes
    - k3d node list

    # Install Flux
    - which flux
    - flux --version
    - flux install --timeout 3m0s
    - kubectl get namespaces,pods,helmrelease,gitrepositories -A

    # Install Big Bang
    - helm upgrade -i bigbang chart -n bigbang --create-namespace --set registryCredentials.username='robot$bigbang' --set registryCredentials.password=${REGISTRY1_PASSWORD}

    # Wait for healthy
    - sleep 5
    - kubectl get namespaces,pods,helmrelease,kustomizations,gitrepositories -A
    - kubectl wait --for=condition=Ready --timeout 300s helmrelease -n bigbang certmanager
    - kubectl wait --for=condition=Ready --timeout 300s helmrelease -n bigbang gatekeeper
    - kubectl wait --for=condition=Ready --timeout 300s helmrelease -n bigbang istio-operator
    - kubectl wait --for=condition=Ready --timeout 300s helmrelease -n bigbang istio
    - kubectl wait --for=condition=Ready --timeout 300s helmrelease -n bigbang eck-operator
    - kubectl wait --for=condition=Ready --timeout 300s helmrelease -n bigbang ek
    - kubectl wait --for=condition=Ready --timeout 300s helmrelease -n bigbang fluent-bit
    - kubectl wait --for=condition=Ready --timeout 300s helmrelease -n bigbang twistlock
    - kubectl wait --for=condition=Ready --timeout 900s helmrelease -n bigbang cluster-auditor
    
    # Show all deployed resources
    - kubectl get all -A

    # Install cypress
#    - npm install cypress
    # Clean up previous cluster
    # Create cluster and wait for deployments and pods
    # - k3d cluster create mycluster --k3s-server-arg "--disable=metrics-server" --k3s-server-arg "--disable=traefik" -p 80:80@loadbalancer -p 443:443@loadbalancer --agents 1 --servers 1
    # - while ! (kubectl get node | grep "agent" > /dev/null); do sleep 3; done
    # - kubectl wait --for=condition=available --timeout 600s -A deployment --all > /dev/null
    # - kubectl wait --for=condition=ready --timeout 600s -A pods --all --field-selector status.phase=Running > /dev/null
    # # Deploy ArgoCD and wait for deployments and pods
    # - kubectl apply -k ./ArgoCD/
    # - |
    #   kubectl patch secret -n argocd argocd-secret -p '{"stringData": { "admin.password": "$2y$12$3EySSrfvhLp7V1833J4fS.kvPNvdxmiofuhHV8spDr98J.EJ/FgJW"}}'
    # - kubectl wait --for=condition=available --timeout 600s -A deployment --all > /dev/null
    # - kubectl wait --for=condition=ready --timeout 600s -A pods --all --field-selector status.phase=Running > /dev/null

  script:
    # Place kubernetes package test here
    - echo "Package tests go here"
    - kubectl get helmrelease -A

  after_script:
    # Delete Cluster
    - k3d cluster delete umbrella
