image: alpine:latest

stages:
  - smoke tests
  - network up
  - cluster up
  - bigbang up
  - tests
  - bigbang down
  - cluster down
  - network down

clean install:
  stage: smoke tests
  script:
    - echo "k3d clean intall smoke tests"


upgrade:
  stage: smoke tests
  script:
    - echo "k3d upgrade smoke tests"
  only:
    - merge_requests

# E2E Matrix
.mr:
  only: [ merge_requests ]

#
# Networking
#
aws|network up:
  extends: .mr
  stage: network up
  script:
    - echo "aws network up"
  needs: []
  when: manual

aws|network down:
  extends: .mr
  stage: network down
  script:
    - echo "aws network down"
  when: always
  needs:
    - rke2|cluster down
    - eks|cluster down

#
# RKE2
#
rke2|cluster up:
  extends: .mr
  stage: cluster up
  script:
    - echo "rke2 cluster up"
  needs:
    - aws|network up

rke2|bigbang up:
  extends: .mr
  stage: bigbang up
  script:
    - echo "rke2 bigbang up"
  needs:
    - rke2|cluster up

rke2|e2e tests:
  extends: .mr
  stage: tests
  script:
    - echo "rke2 e2e tests"
  needs:
    - rke2|bigbang up

rke2|bigbang down:
  extends: .mr
  stage: bigbang down
  script:
    - echo "rke2 bigbang down"
  needs:
    - rke2|e2e tests
  when: always

rke2|cluster down:
  extends: .mr
  stage: cluster down
  script:
    - echo "rke2 cluster down"
  needs:
    - rke2|bigbang down
  when: always

#
# EKS
#
eks|cluster up:
  extends: .mr
  stage: cluster up
  script:
    - echo "eks cluster up"
  needs:
    - aws|network up
  when: manual

eks|bigbang up:
  extends: .mr
  stage: bigbang up
  script:
    - echo "eks bigbang up"
  needs:
    - eks|cluster up

eks|e2e tests:
  extends: .mr
  stage: tests
  script:
    - echo "eks e2e tests"
  needs:
    - eks|bigbang up

eks|bigbang down:
  extends: .mr
  stage: bigbang down
  script:
    - echo "eks bigbang down"
  needs:
    - eks|e2e tests
  when: always

eks|cluster down:
  extends: .mr
  stage: cluster down
  script:
    - echo "eks cluster down"
  needs:
    - eks|bigbang down
  when: always
