image: alpine:latest

stages:
  - smoke tests
  - network up
  - cluster up
  - bigbang up
  - tests
  - bigbang down
  - cluster down
  - network down

clean install:
  stage: smoke tests
  script:
    - echo "k3d clean intall smoke tests"


upgrade:
  stage: smoke tests
  script:
    - echo "k3d upgrade smoke tests"




#
# Networking
#
aws|network up:
  stage: network up
  script:
    - echo "aws network up"

aws|network down:
  stage: network down
  script:
    - echo "aws network down"

#
# RKE2
#
rke2|cluster up:
  stage: cluster up
  script:
    - echo "rke2 cluster up"

rke2|bigbang up:
  stage: bigbang up
  script:
    - echo "rke2 bigbang up"

rke2|e2e tests:
  stage: tests
  script:
    - echo "rke2 e2e tests"

rke2|bigbang down:
  stage: bigbang down
  script:
    - echo "rke2 bigbang down"

rke2|cluster down:
  stage: cluster down
  script:
    - echo "rke2 cluster down"

#
# EKS
#
eks|cluster up:
  stage: cluster up
  script:
    - echo "eks cluster up"

eks|bigbang up:
  stage: bigbang up
  script:
    - echo "eks bigbang up"

eks|e2e tests:
  stage: tests
  script:
    - echo "eks e2e tests"

eks|bigbang down:
  stage: bigbang down
  script:
    - echo "eks bigbang down"

eks|cluster down:
  stage: cluster down
  script:
    - echo "eks cluster down"
