workflow:
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /^wip/'
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /^docs/'
      when: never
    - when: always

image: alpine:latest

stages:
  - smoke tests
  - network up
  - cluster up
  - bigbang up
  - tests
  - bigbang down
  - cluster down
  - network down

clean install:
  stage: smoke tests
  script:
    - echo "k3d clean intall smoke tests"

upgrade:
  stage: smoke tests
  script:
    - echo "k3d upgrade smoke tests"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

# E2E Matrix
.infra fork:
  stage: network up
  needs: []
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^hotfix/'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
      allow_failure: false

.infra create:
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^hotfix/'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

.infra cleanup:
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^hotfix/'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      allow_failure: true
      when: always

#
# Networking
#
# AWS
aws|network up:
  extends: .infra fork
  script:
    - echo "aws network up"

aws|network down:
  extends: .infra cleanup
  stage: network down
  script:
    - echo "aws network down"
  needs:
    - aws|rke2|cluster down
    - eks|cluster down

# Azure
azure|network up:
  extends: .infra fork
  script:
    - echo "azure network up"

azure|network down:
  extends: .infra cleanup
  stage: network down
  script:
    - echo "aws network down"
  needs:
    - azure|rke2|cluster down
    - aks|cluster down

#
# RKE2
#
# AWS
aws|rke2|cluster up:
  extends: .infra create
  stage: cluster up
  script:
    - echo "aws rke2 cluster up"
  needs:
    - aws|network up

aws|rke2|bigbang up:
  extends: .infra create
  stage: bigbang up
  script:
    - echo "rke2 bigbang up"
  needs:
    - aws|rke2|cluster up

aws|rke2|e2e tests:
  extends: .infra create
  stage: tests
  script:
    - echo "rke2 e2e tests"
  needs:
    - aws|rke2|bigbang up

aws|rke2|bigbang down:
  extends: .infra cleanup
  stage: bigbang down
  script:
    - echo "rke2 bigbang down"
  needs:
    - aws|rke2|e2e tests

aws|rke2|cluster down:
  extends: .infra cleanup
  stage: cluster down
  script:
    - echo "rke2 cluster down"
  needs:
    - aws|rke2|bigbang down

# Azure
azure|rke2|cluster up:
  extends: .infra create
  stage: cluster up
  script:
    - echo "azure rke2 cluster up"
  needs:
    - azure|network up

azure|rke2|bigbang up:
  extends: .infra create
  stage: bigbang up
  script:
    - echo "azure rke2 bigbang up"
  needs:
    - azure|rke2|cluster up

azure|rke2|e2e tests:
  extends: .infra create
  stage: tests
  script:
    - echo "azure rke2 e2e tests"
  needs:
    - azure|rke2|bigbang up

azure|rke2|bigbang down:
  extends: .infra cleanup
  stage: bigbang down
  script:
    - echo "azure rke2 bigbang down"
  needs:
    - azure|rke2|e2e tests

azure|rke2|cluster down:
  extends: .infra cleanup
  stage: cluster down
  script:
    - echo "azure rke2 cluster down"
  needs:
    - azure|rke2|bigbang down

#
# EKS
#
eks|cluster up:
  extends: .infra create
  stage: cluster up
  script:
    - echo "eks cluster up"
  needs:
    - aws|network up

eks|bigbang up:
  extends: .infra create
  stage: bigbang up
  script:
    - echo "eks bigbang up"
    - exit 1
  needs:
    - eks|cluster up

eks|e2e tests:
  extends: .infra create
  stage: tests
  script:
    - echo "eks e2e tests"
  needs:
    - eks|bigbang up

eks|bigbang down:
  extends: .infra cleanup
  stage: bigbang down
  script:
    - echo "eks bigbang down"
  needs:
    - eks|e2e tests

eks|cluster down:
  extends: .infra cleanup
  stage: cluster down
  script:
    - echo "eks cluster down"
  needs:
    - eks|bigbang down

#
# AKS
#
aks|cluster up:
  extends: .infra create
  stage: cluster up
  script:
    - echo "aks cluster up"
  needs:
    - azure|network up

aks|bigbang up:
  extends: .infra create
  stage: bigbang up
  script:
    - echo "aks bigbang up"
    - exit 1
  needs:
    - aks|cluster up

aks|e2e tests:
  extends: .infra create
  stage: tests
  script:
    - echo "aks e2e tests"
  needs:
    - aks|bigbang up

aks|bigbang down:
  extends: .infra cleanup
  stage: bigbang down
  script:
    - echo "aks bigbang down"
  needs:
    - aks|e2e tests

aks|cluster down:
  extends: .infra cleanup
  stage: cluster down
  script:
    - echo "aks cluster down"
  needs:
    - aks|bigbang down