image: alpine:latest

stages:
  - smoke tests
  - network up
  - cluster up
  - bigbang up
  - tests
  - bigbang down
  - cluster down
  - network down

clean install:
  stage: smoke tests
  script:
    - echo "k3d clean intall smoke tests"

upgrade:
  stage: smoke tests
  script:
    - echo "k3d upgrade smoke tests"
  only:
    - merge_requests

# E2E Matrix
.mr:
#  only: [ merge_requests ]
#  except:
#    variables:
#      # Don't run on documentation branches
#      - $CI_COMMIT_REF_NAME =~ /^docs-/
#
#      # Don't run when 'wip' is in commit message
#      - $CI_COMMIT_MESSAGE =~ /^wip/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

.cleanup:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
      allow_failure: true

#
# Networking
#
aws|network up:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
      allow_failure: true
  stage: network up
  script:
    - echo "aws network up"
  needs: []

aws|network down:
  extends: .cleanup
  stage: network down
  script:
    - echo "aws network down"
  needs:
    - rke2|cluster down
    - eks|cluster down

#
# RKE2
#
rke2|cluster up:
  extends: .mr
  stage: cluster up
  script:
    - echo "rke2 cluster up"
  needs:
    - aws|network up

rke2|bigbang up:
  extends: .mr
  stage: bigbang up
  script:
    - echo "rke2 bigbang up"
  needs:
    - aws|network up
    - rke2|cluster up

rke2|e2e tests:
  extends: .mr
  stage: tests
  script:
    - echo "rke2 e2e tests"
  needs:
    - aws|network up
    - rke2|bigbang up

rke2|bigbang down:
  extends: .cleanup
  stage: bigbang down
  script:
    - echo "rke2 bigbang down"
  needs:
    - aws|network up
    - rke2|e2e tests

rke2|cluster down:
  extends: .cleanup
  stage: cluster down
  script:
    - echo "rke2 cluster down"
  needs:
    - aws|network up
    - rke2|bigbang down

#
# EKS
#
eks|cluster up:
  extends: .mr
  stage: cluster up
  script:
    - echo "eks cluster up"
  needs:
    - aws|network up

eks|bigbang up:
  extends: .mr
  stage: bigbang up
  script:
    - echo "eks bigbang up"
  needs:
    - aws|network up
    - eks|cluster up

eks|e2e tests:
  extends: .mr
  stage: tests
  script:
    - echo "eks e2e tests"
  needs:
    - aws|network up
    - eks|bigbang up

eks|bigbang down:
  extends: .cleanup
  stage: bigbang down
  script:
    - echo "eks bigbang down"
  needs:
    - aws|network up
    - eks|e2e tests

eks|cluster down:
  extends: .cleanup
  stage: cluster down
  script:
    - echo "eks cluster down"
  needs:
    - aws|network up
    - eks|bigbang down
