apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: es
spec:
  elasticsearch:
    port: 9200
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    host: bigbang-es-http.logging.svc.cluster.local
    password:
      valueFrom:
        secretKeyRef:
          name: bigbang-es-elastic-user
          key: elastic
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    user: elastic
