{{- if and (not .Values.offline) (or .Values.logging.enabled .Values.clusterAuditor.enabled) }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: elasticsearch-kibana
  namespace: {{ .Release.Namespace }}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.elasticsearchkibana.git.repo }}
  ref:
    {{- include "validRef" .Values.elasticsearchkibana.git | nindent 4 }}
  {{ include "gitIgnore" . }}
{{- end }}
