{{- if or .Values.logging.enabled .Values.clusterAuditor.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    {{- if .Values.istio.enabled }}{{- include "bigbang.istioInjectionLabel" .  | nindent 4}}{{- end }}
{{- end }}