{{- if or .Values.logging.enabled .Values.clusterAuditor.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bigbang.name" . }}-registry-credentials
  namespace: logging
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}