{{- if and .Values.logging.enabled .Values.logging.sso.enabled .Values.sso.certificate_authority}}
apiVersion: v1
kind: Secret
metadata:
  name: tls-ca-sso
  namespace: logging
type: Opaque
data:
  ca.pem: {{ .Values.sso.certificate_authority | b64enc }}
{{- end }}