{{- if or .Values.logging.enabled .Values.clusterAuditor.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.logging "name" "ek" "defaults" (include "bigbang.defaults.logging" .)) }}
{{- end }}

{{- define "bigbang.defaults.logging" -}}
hostname: {{ .Values.hostname }}
istio:
  enabled: {{ .Values.istio.enabled }}

{{- with .Values.logging.sso }}
{{- if .enabled }}
sso:
  enabled: {{ .enabled }}
  client_id: {{ .client_id | quote }}
  client_secret: {{ .client_secret | default "no-secret" }}
  oidc:
    host: {{ .oidc.host | default $.Values.sso.oidc.host | quote }}
    realm: {{ .oidc.realm | default $.Values.sso.oidc.realm | quote }}
  issuer: {{ .issuer | quote }}
  auth_url: {{ .auth_url | quote }}
  token_url: {{ .token_url | quote }}
  userinfo_url: {{ .userinfo_url | quote }}
  jwkset_url: {{ .jwkset_url | quote }}
  claims_principal: {{ .claims_principal | quote }}
  claims_principal_pattern: {{ .claims_principal_pattern | quote }}
  signature_algorithm: {{ .signature_algorithm | quote }}
  endsession_url: {{ .endsession_url | quote }}
  claims_group: {{ .claims_group | quote }}
  claims_mail: {{ .claims_mail | quote }}
{{- end }}
{{- end }}

kibana:
  version: 7.9.2
  imagePullSecrets:
    - name: private-registry

elasticsearch:
  version: 7.9.2
  imagePullSecrets:
    - name: private-registry
{{- end -}}
