{{- $fluxSettingsArgo := merge .Values.addons.argocd.flux .Values.flux -}}
{{- if .Values.addons.argocd.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: argocd
  chart:
    spec:
      chart: {{ .Values.addons.argocd.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: argocd
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsArgo | nindent 2 }}

  valuesFrom:
    - name: {{ .Release.Name }}-argocd-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-argocd-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-argocd-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or .Values.istio.enabled .Values.monitoring.enabled }}
  dependsOn:
    {{- include "bigbang.istioDependsOn" . | nindent 4 }}
    {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
