{{- if .Values.addons.argocd.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    {{- if .Values.istio.enabled }}{{- include "bigbang.istioInjectionLabel" .  | nindent 4 }}{{- else }}
    istio-injection: disabled
    {{- end }}
  name: argocd
{{- end }}
