{{- if .Values.addons.argocd.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    {{- if eq (dig "istio" "injection" "enabled" .Values.addons.argocd) "enabled" }}
    {{- include "bigbang.istioInjectionLabel" . | nindent 4 }}
    {{- else }}
    istio-injection: disabled
    {{- end }}
  name: argocd
{{- end }}
