---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: "core"
  name: http
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 443
      protocol: TCP
    - port: 5556
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: "core"
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 6379
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Egress
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: "core"
  name: ui
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 2746
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: "core"
  name: sentinel
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 26379
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Egress
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: "core"
  name: grpc
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 5557
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Egress
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: "core"
  name: metrics
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 5558
      protocol: TCP
    - port: 8083
      protocol: TCP
    - port: 8084
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Egress
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: "core"
  name: server
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 8081
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Egress
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: "core"
  name: deny-ingress
  namespace: flux-system
spec:
  egress:
  - {}
  ingress:
  - from:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---