apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  addonComponents:
    kiali:
      enabled: true
    tracing:
      enabled: true
  hub: registry1.dsop.io/ironbank/opensource/istio
  meshConfig:
    accessLogFile: /dev/stdout
  profile: default
  tag: 1.7.3
  values:
    global:
      imagePullSecrets:
      - private-registry
    kiali:
      image: kiali
      dashboard:
        auth:
          strategy: anonymous
      hub: registry1.dsop.io/ironbank/opensource/kiali
      tag: v1.23.0
    sidecarInjectorWebhook:
      neverInjectSelector:
      - matchExpressions:
        - key: app.kubernetes.io/component
          operator: In
          values: [fluentd-configcheck]
      rewriteAppHTTPProbe: true
    tracing:
      jaeger:
        image: all-in-one
        hub: registry1.dsop.io/ironbank/opensource/jaegertracing
        tag: 1.19.2
