apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  profile: default
  hub: registry1.dsop.io/ironbank/opensource/istio
  tag: 1.7.3
  meshConfig:
    accessLogFile: /dev/stdout
  addonComponents:
    kiali:
      enabled: true

    tracing:
      enabled: true

  values:
    global:
      imagePullSecrets:
        - private-registry


    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
      neverInjectSelector:
        - matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values: [fluentd-configcheck]

    kiali:
      hub: registry1.dsop.io/ironbank/opensource/kiali
      image: kiali
      tag: v1.23.0
      dashboard:
        auth:
          strategy: anonymous
    tracing:
      jaeger:
        hub: registry1.dsop.io/ironbank/opensource/jaegertracing
        image: all-in-one
        tag: 1.19.2
