{{- $fluxSettingsLoki := merge .Values.logging.flux .Values.flux -}}
{{- if and .Values.logging.enabled .Values.logging.loki }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: logging
  chart:
    spec:
      chart: {{ .Values.logging.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: grafana-loki
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsLoki | nindent 2 }}

  {{- if .Values.logging.postRenderers }}
  postRenderers:
  {{ toYaml .Values.logging.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-loki-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-loki-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-loki-values
      kind: Secret
      valuesKey: "overlays"

  dependsOn:
    {{- if  .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
    {{- end }}

    {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}
{{- end }}
