apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      interval: 5m
      sourceRef:
        name: prometheus-community
        namespace: flux-system
        kind: HelmRepository
      version: 10.1.2
  interval: 2m
  values:
    alertmanager:
      alertmanagerSpec:
        image:
          repository: registry1.dsop.io/ironbank/opensource/prometheus/alertmanager
          tag: v0.21.0
      enabled: true
    fullnameOverride: monitoring
    global:
      imagePullSecrets:
      - name: private-registry
    grafana:
      image:
        repository: registry1.dsop.io/ironbank/opensource/grafana/grafana
        tag: 7.1.3-1
      enabled: true
    prometheus:
      enabled: true
      prometheusSpec:
        # service port naming conventions
        portName: http-web
    prometheusOperator:
      image:
        repository: registry1.dsop.io/ironbank/opensource/coreos/prometheus-operator
        tag: v0.42.1
      configmapReloadImage:
        repository: registry1.dsop.io/ironbank/opensource/jimmidyson/configmap-reload
        tag: v0.4.0
      createCustomResource: true
      enabled: true
      manageCrds: true
  valuesFrom:
  - name: env-values
    kind: ConfigMap
    optional: true
  - name: env-values
    kind: Secret
    optional: true
