stages:
  - package tests

package tests:
  stage: package tests
  tags:
    - bigbang
    - dogfood
    - privileged

  image:
    name: registry.dso.mil/platform-one/big-bang/pipeline-templates/pipeline-templates/k3d-builder:afdd9b77
  services:
    - registry.dso.mil/platform-one/big-bang/pipeline-templates/pipeline-templates/docker:dind
  variables:
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  artifacts:
    when: always
    paths:
      - tests/cypress/screenshots
      - tests/cypress/videos
    expire_in: 3 days

  before_script:
    - |
      mkdir cypress-tests/
      cd cypress-tests/
      for i in "$(grep -r "enabled: true" tests/ci/k3d/values.yaml -B 1 | grep -v "enabled: true" | sed -e 's/:.*//' | sed 's/^ *//g')"
      do
          git -C cypress-tests/ clone -b $(yq r "chart/values.yaml" "${i}.git.tag") $(yq r "chart/values.yaml" "${i}.git.repo")
          git -C cypress-tests/ clone -b $(yq r "chart/values.yaml" "addons.${i}.git.tag") $(yq r "chart/values.yaml" "addons.${i}.git.repo") 
      done

  script:
    - |
      for dir in cypress-tests/*/
      do
        if [ -f "${dir}tests/cypress.json" ]; then
          cd ${dir}tests && cypress run
        fi
      done

