{{- if .Values.nifi.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: {{ .Release.Name }}-nifi
  name: nifi

# For il2-registry deploy token
---
apiVersion: v1
kind: Secret
metadata:
  name: il2-registry
  namespace: nifi
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret2" . }}
  {{- end }}