{{- if .Values.addons.argocd.enabled  }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  ignore: |
    # exclude file extensions
    /**/*.md
    /**/*.txt
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.addons.keycloak.git.repo }}
  ref:
    {{- include "validRef" .Values.addons.keycloak.git | nindent 4 }}
{{- if .Values.addons.keycloak.git.secret }}
  secretRef:
    name: {{ .Values.addons.keycloak.git.secret | quote }}
{{- end }}
{{- end }}
