apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  filters:
  - tag_normaliser: {}
  globalOutputRefs:
  - es
  match:
  - select:
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
