apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: globals
    namespace: flux-system
    behavior: merge
    envs:
      - globals.env