{{- if .Values.addons.velero.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: velero
  {{- if .Values.istio.enabled }}
  labels:
    istio-injection: enabled
  {{- end }}

{{- if ( include "imagePullSecret" . ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: velero
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}
