{{- if .Values.addons.velero.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: velero
  chart:
    spec:
      chart: {{ .Values.addons.velero.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: velero
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}
  values:
    imagePullSecrets:
    - name: private-registry

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "velero.yaml"
{{- end }}