{{- if or .Values.addons.gitlab.enabled .Values.addons.gitlabRunner.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/component: "developer-tools"
    {{- include "commonLabels" . | nindent 4}}
    {{- if .Values.istio.enabled }}
    istio-injection: enabled
    {{- end }}
  name: gitlab
{{- end }}
