{{- if .Values.addons.gitlab.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: gitlab
  name: gitlab
---
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: gitlab
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
---
# create sso secret
{{- if .Values.addons.gitlab.sso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-sso-provider
  namespace: gitlab
type: kubernetes.io/opaque
stringData:
  gitlab-sso.json: {{ toYaml .Values.addons.gitlab.sso.secret | indent 2 }}
{{- end }}
---
# create database secret
{{- if .Values.addons.gitlab.database.external }}
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-database
    namespace: gitlab
type: kubernetes.io/opaque
stringData:
    PGPASSWORD: {{ .Values.addons.gitlab.database.password }}
{{- end }}
---
# create object storage secret
{{- if .Values.addons.gitlab.objectstorage.external }}
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage
    namespace: gitlab
type: kubernetes.io/opaque
stringData:
    rails: {{ toYaml .Values.addons.gitlab.objectstorage.secrets.rails | indent 4 }}
    registry: {{ toYaml .Values.addons.gitlab.objectstorage.secrets.registry | indent 4 }}
    backups: {{ toYaml .Values.addons.gitlab.objectstorage.secrets.backups | indent 4 }}
{{- end }}

{{- end }}