{{- if .Values.addons.gitlab.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: gitlab
  name: gitlab
---
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: gitlab
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
---
# create sso secret. The assumption is OIDC
{{- if .Values.addons.gitlab.sso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-sso-provider
  namespace: gitlab
type: kubernetes.io/opaque
stringData:
  gitlab-sso.json: |-
    {
      "name": "openid_connect",
      "label": "{{ .Values.addons.gitlab.sso.label }}",
      "args": {
        "name": "openid_connect",
        "scope": [
          "Gitlab"
        ],
        "response_type": "code",
        "issuer": "{{ .Values.addons.gitlab.sso.issuer }}",
        "client_auth_method": "query",
        "discovery": true,
        "uid_field": "preferred_username",
        "client_options": {
          "identifier": "{{ .Values.addons.gitlab.sso.clientId }}",
          "secret": "{{ .Values.addons.gitlab.sso.label }}",
          "redirect_uri": "{{ .Values.addons.gitlab.sso.redirectUri }}",
          "end_session_endpoint": "{{ .Values.addons.gitlab.sso.endSessionEndpoint }}"
        }
      }
    }
{{- end }}
---
# create database secret
{{- if .Values.addons.gitlab.database.external }}
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-database
    namespace: gitlab
type: kubernetes.io/opaque
stringData:
    PGPASSWORD: {{ .Values.addons.gitlab.database.password }}
{{- end }}
---
# create object storage secret
{{- if .Values.addons.gitlab.objectstorage.external }}
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage
    namespace: gitlab
type: kubernetes.io/opaque
stringData:
    rails: {{ toYaml .Values.addons.gitlab.objectstorage.rails.connection.secret | indent 4 }}
    registry: {{ toYaml .Values.addons.gitlab.objectstorage.registry.connection.secret | indent 4 }}
    backups: {{ toYaml .Values.addons.gitlab.objectstorage.backups.connection.secret | indent 4 }}
{{- end }}

{{- end }}