{{- if and (or .Values.addons.gitlab.enabled .Values.addons.gitlabRunner.enabled) .Values.addons.gitlab.sso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tls-ca-sso
  namespace: gitlab
type: Opaque
data:
  ca.pem: {{ .Values.sso.certificate_authority | b64enc }}
{{- end }}