apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus
spec:
  gateways:
  - main.istio-system.svc.cluster.local
  hosts:
  - "prometheus.hostname" # {"$kpt-set":"prometheus-hostname"}
  http:
  - route:
    - destination:
        port:
          number: 9090
        host: monitoring-prometheus
