apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bigbang
spec:
  # Increase reconciliation interval for dev
  interval: 1m0s
  values:
    hostname: bigbang.dev

    # Tune flux for dev
    flux:
      interval: 1m
      rollback:
        cleanupOnFail: false

    logging:
      # Directly modify chart values for dev workloads
      values:
        elasticsearch:
          master:
            count: 1
            persistence:
              size: 5Gi
          data:
            count: 1
            persistence:
              size: 5Gi

    # Disable packages from deploying (for example while you're testing)
    twistlock:
      enabled: false