{{- if .Values.addons.gitlabRunner.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runner

{{- if ( include "imagePullSecret" . ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: gitlab-runner
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}