{{- if or .Values.addons.gitlab.enabled .Values.addons.gitlabRunner.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: gitlab-runner
    app.kubernetes.io/component: "developer-tools"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: enabled
  name: gitlab-runner
{{- end }}