{{- if .Values.addons.gitlabRunner.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.gitlabRunner "name" "gitlab-runner" "defaults" (include "bigbang.defaults.gitlab-runner" .)) }}
{{- end }}

{{- define "bigbang.defaults.gitlab-runner" -}}
imagePullSecrets:
- name: private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}
{{- end -}}
