{{- if .Values.certmanager.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: certmanager
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: cert-manager
  chart:
    spec:
      chart: chart
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: certmanager
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  values:
    global:
      logLevel: 2

      {{- if and (ne .Values.registryCredentials.username "") (ne .Values.registryCredentials.password "") }}
      imagePullSecrets: [ name: private-registry ]
      {{- end }}

  valuesFrom:
  - name: values
    kind: Secret
    valuesKey: "certmanager.yaml"
{{- end }}