{{- if or .Values.gatekeeper.enabled .Values.clusterAuditor.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: docs

---
{{- if and (ne .Values.registryCredentials.username "") (ne .Values.registryCredentials.password "") }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: docs
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}