#include:
#  - project: 'platform-one/big-bang/pipeline-templates/umbrella-templates'
#    file: '/jobs/rke2/tf-cluster-up.yaml'
#    ref: rke2

stages:
  - plan
  - apply
  - destroy

rke2:plan:
  stage: plan
  script:
    - echo "plan"
    - export
    - echo "afile" > saveme.txt
  artifacts:
    paths:
      - saveme.txt

rke2:apply:
  stage: apply
  script:
    - echo "apply"
  environment:
    name: rke2/${CI_COMMIT_REF_NAME}
    auto_stop_in: 1 hour

rke2:destroy:
  stage: destroy
  script:
    - echo "destroy"
  environment:
    name: rke2/${CI_COMMIT_REF_NAME}
    action: stop