#include:
#  - project: 'platform-one/big-bang/pipeline-templates/umbrella-templates'
#    file: '/jobs/rke2/tf-cluster-up.yaml'
#    ref: rke2

stages:
  - plan
  - apply
  - destroy

rke2:plan:
  stage: plan
  script:
    - echo "plan"
    - export
    - echo "afile" > saveme.txt
  artifacts:
    paths:
      - saveme.txt

rke2:apply:
  stage: apply
  needs: [ plan ]
  script:
    - echo "apply"

rke2:destroy:
  stage: destroy
  needs: [ apply ]
  script:
    - echo "destroy"