resources:
  - flux-system
  - istio
  - observability
  - cert-manager
  - gatekeeper

patches:
    # Add common parameters to all HelmReleases
  - target:
      kind: HelmRelease
      group: helm.toolkit.fluxcd.io
    patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: common
      spec:
        test:
          enable: false
        install:
          remediation:
            retries: 5
        upgrade:
          remediation:
            retries: 3
            remediateLastFailure: true
          cleanupOnFail: true
        rollback:
          timeout: 1m
          cleanupOnFail: true

configMapGenerator:
  - name: globals
    namespace: flux-system

vars:
  - name: hostname
    objref: { kind: ConfigMap, name: globals, apiVersion: v1 }
    fieldref:
      fieldpath: data.hostname

configurations:
  - config.yaml