{{- if .Values.addons.nexus.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: nexus-repository-manager
  labels:
    {{- include "bigbang.istioInjectionLabel" . | nindent 4 }}
    app.kubernetes.io/name: "nexus-repository-manager"
    app.kubernetes.io/component: "developer-tools"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}
