{{- if .Values.addons.nexus.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nexus-repository-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "nexus-repository-manager"
    app.kubernetes.io/component: "developer-tools"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: nexus-repository-manager
  releaseName: nexus-repository-manager
  chart:
    spec:
      chart: {{ .Values.addons.nexus.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: nexus-repository-manager
        namespace: {{ .Release.Namespace }}
  timeout: 10m
  interval: 10m
  test:
    enable: false
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: true
  valuesFrom:
    - name: {{ .Release.Name }}-nexus-repository-manager-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-nexus-repository-manager-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-nexus-repository-manager-values
      kind: Secret
      valuesKey: "overlays"

  {{ if or .Values.istio.enabled .Values.monitoring.enabled }}
  dependsOn:
  {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}
