{{- if .Values.addons.nexusRepositoryManager.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nexus-repository-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "nexus-repository-manager"
    app.kubernetes.io/component: "developer-tools"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: nexus-repository-manager
  releaseName: nexus-repository-manager
  interval: 10m
  chart:
    spec:
      chart: {{ .Values.addons.nexusRepositoryManager.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: nexus-repository-manager
{{- if .Values.istio.enabled }}
  dependsOn:
  - name: istio
    namespace: bigbang
{{- end }}
{{- end }}
