{{- if and  .Values.addons.nexus.enabled .Values.addons.nexus.sso.enabled .Values.sso.certificate_authority }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.sso.secretName}}
  namespace: anchore
type: Opaque
data:
  ca.pem: {{ .Values.sso.certificate_authority | b64enc }}
{{- end }}