{{- if .Values.addons.anchore.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: anchore
    app.kubernetes.io/component: "security"
    {{- include "commonLabels" . | nindent 4}}
    {{- if .Values.istio.enabled }}{{- include "bigbang.istioInjectionLabel" .  | nindent 4 }}{{- end }}
  name: anchore
{{- end }}