# Source: istio-operator/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: istio-operator
  labels:
    istio-injection: disabled
    istio-operator-managed: Reconcile
---
# Source: istio-operator/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-operator
  namespace: istio-operator
---
# Source: istio-operator/templates/crds.yaml
# SYNC WITH manifests/charts/base/files
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: istiooperators.install.istio.io
  labels:
    release: istio
spec:
  group: install.istio.io
  names:
    kind: IstioOperator
    plural: istiooperators
    shortNames:
    - iop
    singular: istiooperator
  scope: Namespaced
  versions:
  - name: v1alpha1
    additionalPrinterColumns:
    - name: Revision
      type: string
      description: Istio control plane revision
      jsonPath: .spec.revision
    - name: Status
      type: string
      description: IOP current state
      jsonPath: .status.status
    - name: Age
      type: date
      description: "CreationTimestamp is a timestamp representing the server time
        when this object was created. It is not guaranteed to be set in happens-before
        order across separate operations. Clients may not set this value. It is represented
        in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for
        lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"
      jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
            description: "APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources"
          kind:
            type: string
            description: "Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
          spec:
            type: object
            description: "Specification of the desired state of the istio control
              plane resource. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status"
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            description: "Status describes each of istio control plane component status
              at the current time. 0 means NONE, 1 means UPDATING, 2 means HEALTHY,
              3 means ERROR, 4 means RECONCILING. More info: https://github.com/istio/api/blob/master/operator/v1alpha1/istio.operator.v1alpha1.pb.html
              & https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status"
            x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
---
# Source: istio-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-operator
  creationTimestamp: null
rules:
- resources:
  - '*'
  # istio groups
  apiGroups:
  - authentication.istio.io
  verbs:
  - '*'
- resources:
  - '*'
  apiGroups:
  - config.istio.io
  verbs:
  - '*'
- resources:
  - '*'
  apiGroups:
  - install.istio.io
  verbs:
  - '*'
- resources:
  - '*'
  apiGroups:
  - networking.istio.io
  verbs:
  - '*'
- resources:
  - '*'
  apiGroups:
  - security.istio.io
  verbs:
  - '*'
- resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  # k8s groups
  apiGroups:
  - admissionregistration.k8s.io
  verbs:
  - '*'
- resources:
  - customresourcedefinitions.apiextensions.k8s.io
  - customresourcedefinitions
  apiGroups:
  - apiextensions.k8s.io
  verbs:
  - '*'
- resources:
  - daemonsets
  - deployments
  - deployments/finalizers
  - ingresses
  - replicasets
  - statefulsets
  apiGroups:
  - apps
  - extensions
  verbs:
  - '*'
- resources:
  - horizontalpodautoscalers
  apiGroups:
  - autoscaling
  verbs:
  - '*'
- resources:
  - servicemonitors
  apiGroups:
  - monitoring.coreos.com
  verbs:
  - get
  - create
  - update
- resources:
  - poddisruptionbudgets
  apiGroups:
  - policy
  verbs:
  - '*'
- resources:
  - clusterrolebindings
  - clusterroles
  - roles
  - rolebindings
  apiGroups:
  - rbac.authorization.k8s.io
  verbs:
  - '*'
- resources:
  - configmaps
  - endpoints
  - events
  - namespaces
  - pods
  - persistentvolumeclaims
  - secrets
  - services
  - serviceaccounts
  apiGroups:
  - ""
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
# Source: istio-operator/templates/clusterrole_binding.yaml
kind: ClusterRoleBinding
metadata:
  name: istio-operator
roleRef:
  name: istio-operator
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: istio-operator
  namespace: istio-operator
  kind: ServiceAccount
---
# Source: istio-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: istio-operator
  namespace: istio-operator
  labels:
    name: istio-operator
spec:
  selector:
    name: istio-operator
  ports:
  - name: http-metrics
    port: 8383
    targetPort: 8383
---
# Source: istio-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-operator
  namespace: istio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: istio-operator
  template:
    metadata:
      labels:
        name: istio-operator
    spec:
      serviceAccountName: istio-operator
      containers:
      - name: istio-operator
        image: docker.io/istio/operator:1.7.4-distroless
        command:
        - operator
        - server
        env:
        - name: WATCH_NAMESPACE
          value: "istio-system"
        - name: LEADER_ELECTION_NAMESPACE
          value: "istio-operator"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "istio-operator"
        - name: WAIT_FOR_RESOURCES_TIMEOUT
          value: "300s"
        - name: REVISION
          value: ""
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1337
          runAsNonRoot: true
          runAsUser: 1337
