{{- if .Values.documentation.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: documentation
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: documentation 
  chart:
    spec:
      chart: chart
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: documentation
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "documentation.yaml"

  values:
    packages:
    {{- if .Values.clusterAuditor.enabled }}
    - name: cluster-auditor
      repo: {{ .Values.clusterAuditor.git.repo }}
      branch: {{ .Values.clusterAuditor.git.branch }}
      path: docs
    {{- end }}
    {{- if .Values.addons.argocd.enabled }}
    - name: argocd
      repo: {{ .Values.addons.argocd.git.repo }}
      branch: {{ .Values.addons.argocd.git.branch }}
      path: docs
    {{- end }}
     {{- if or .Values.logging.enabled .Values.clusterAuditor.enabled }}
    - name: elastic-kibana
      repo: https://repo1.dsop.io/platform-one/big-bang/apps/core/elasticsearch-kibana.git
      branch: main
      path: docs
    {{- end }}
    {{- if .Values.gatekeeper.enabled }}
    - name: opa-gatekeeper
      repo: https://repo1.dsop.io/platform-one/big-bang/apps/core/policy.git
      branch: main
      path: docs
    {{- end }}
    imagePullSecrets:
      - name: private-registry
  dependsOn:
  {{- if .Values.istio.enabled }}
  - name: istio
    namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}