{{- if .Values.documentation.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: documentation
  namespace: {{ .Release.Namespace }}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.documentation.git.repo }}
  ref:
    branch: kenna-doc-hardened
{{- end }}
