---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: bigbang-monitoring
spec:
  path: './instance/monitoring'
  healthChecks:
    - kind: HelmRelease
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      name: monitoring
      namespace: monitoring