{{- if .Values.addons.mattermostoperator.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mattermost-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mattermost-operator
    app.kubernetes.io/component: "collaboration-tools"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: mattermost-operator
  chart:
    spec:
      chart: {{ .Values.addons.mattermostoperator.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: mattermost-operator
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "mattermostoperator.yaml"

  values:
    imagePullSecrets:
      - name: private-registry
{{- end }}
