{{- if or .Values.addons.mattermostoperator.enabled .Values.addons.mattermost.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.mattermostoperator "name" "mattermost-operator" "defaults" (include "bigbang.defaults.mattermostoperator" .)) }}
{{- end }}

{{- define "bigbang.defaults.mattermostoperator" -}}
imagePullSecrets:
  - name: private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

istio:
  enabled: {{ .Values.istio.enabled }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}
{{- end -}}
