{{- if or (not .Values.global.offline) .Values.monitoring.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: {{ .Release.Name }}-monitoring
  namespace: {{ .Release.Namespace }}
spec:
  ignore: |
    # exclude file extensions
    /**/*.md
    /**/*.txt
    /**/*.sh
  interval: {{ .Values.global.interval }}
  ref:
    branch: {{ .Values.monitoring.git.branch }}
  url: {{ .Values.monitoring.git.repo }}
{{- end }}
