{{- if .Values.monitoring.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: monitoring
  chart:
    spec:
      chart: charts/kube-prometheus-stack
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: monitoring
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "monitoring.yaml"

  values:
    fullnameOverride: monitoring

    global:
      imagePullSecrets:
        - name: private-registry

    alertmanager:
      alertmanagerSpec:
        image:
          repository: registry1.dsop.io/ironbank/opensource/prometheus/alertmanager
          tag: v0.21.0
      enabled: true

    grafana:
    # https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/_pod.tpl#L148-L151

      image:
        repository: registry1.dsop.io/ironbank/opensource/grafana/grafana
        tag: 7.1.3-1
        pullSecrets:
        - private-registry
      enabled: true

    prometheus:
      enabled: true
      prometheusSpec:
        # service port naming conventions
        portName: http-web

    prometheusOperator:
      image:
        repository: registry1.dsop.io/ironbank/opensource/coreos/prometheus-operator
        tag: v0.42.1
      configmapReloadImage:
        repository: registry1.dsop.io/ironbank/opensource/jimmidyson/configmap-reload
        tag: v0.4.0
      createCustomResource: true
      enabled: true
      manageCrds: true

  # TODO: DRY this up
  {{- if .Values.gatekeeper.enabled }}
  dependsOn:
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}