{{- if .Values.monitoring.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: monitoring
  chart:
    spec:
      chart: {{ .Values.monitoring.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: monitoring
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "monitoring.yaml"

  values:
    hostname: {{ .Values.hostname }}
    istio:
      enabled: {{ .Values.istio.enabled }}
    global:
      imagePullSecrets:
        - name: private-registry
#    sso:
#      enabled: {{ .Values.sso.enabled }}}}
#      namespace: {{ .Values.sso.namespace }}
#      selector: {{- with .Values.sso.selector }}
    kubePrometheusStack:
      grafana:
        image:
          pullSecrets:
          - private-registry
        envFromSecret: oathinfo
        grafana.ini:
          server:
            # The root URL must be set with the proper url to enable oauth login
            root_url: {{ .Values.hostname }}
          auth:
            # URL to redirect the user to after sign out
            signout_redirect_url: https://login.dsop.io/auth/realms/baby-yoda/protocol/openid-connect/logout
          auth.generic_oauth:
            enabled: true
            client_id: ${CLIENT_ID}
            client_secret:
            scopes: Grafana
            auth_url: https://login.dsop.io/auth/realms/baby-yoda/protocol/openid-connect/auth
            token_url: https://login.dsop.io/auth/realms/baby-yoda/protocol/openid-connect/token
            api_url: https://login.dsop.io/auth/realms/baby-yoda/protocol/openid-connect/userinfo
            allow_sign_up: true
            role_attribute_path: Viewer

    prometheus-node-exporter:
      serviceAccount:
        imagePullSecrets:
        - name: private-registry
    kube-state-metrics:
      imagePullSecrets:
      - name: private-registry

  # TODO: DRY this up
  {{- if or .Values.gatekeeper.enabled .Values.istio.enabled }}
  dependsOn:
  {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}