{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

{{- if and (ne .Values.registryCredentials.username "") (ne .Values.registryCredentials.password "") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: monitoring
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}

{{- if .Values.monitoring.sso.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ssosecrets
  namespace: monitoring
type: Opaque
data:
  CLIENT_ID: { .Values.monitoring.sso.clientid }}
  CLIENT_SECRET: {{ .Values.monitoring.sso.clientsecret }}
  {{- end }}
{{- end }}