{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    {{- if eq (dig "istio" "injection" "enabled" .Values.monitoring) "enabled" }}
    {{- include "bigbang.istioInjectionLabel" . | nindent 4 }}
    {{- else }}
    istio-injection: disabled
    {{- end }}
{{- end }}
