{{- if and (or .Values.monitoring.enabled) .Values.monitoring.sso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tls-ca-sso
  namespace: monitoring
type: Opaque
data:
  ca.pem: {{ .Values.sso.certificate_authority | b64enc }}
{{- end }}