{{- if .Values.monitoring.sso.enabled }}
# probably want to get rid of this eventually
apiVersion: v1
kind: Secret
metadata:
  name: tls-ca-sso
  namespace: monitoring
type: Opaque
data:
  ca.pem: {{ .Values.sso.certificate_authority | b64enc }}
{{- end }}