{{- if .Values.jaeger.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: jaeger
  chart:
    spec:
      chart: {{ .Values.jaeger.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: jaeger
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "jaeger.yaml"

  values:
    imagePullSecrets:
      - name: private-registry
    hostname: {{ .Values.hostname }}
    istio:
      enabled: {{ .Values.istio.enabled }}
    monitoring:
      enabled: {{ .Values.monitoring.enabled }}
    elasticsearch:
      enabled: true
    {{- if .Values.jaeger.sso.enabled }}
    jaeger:
      spec:
        allInOne:
          labels:
            protect: keycloak
        query:
          labels:
            protect: keycloak
    {{- end }}
  {{ if or .Values.istio.enabled .Values.monitoring.enabled }}
  dependsOn:
  {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.jaeger.sso.enabled }}
    - name: authservice
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}
