{{- if .Values.jaeger.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger
  labels:
    istio-injection: enabled
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: "application-utilities"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}