{{- if .Values.jaeger.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger
  labels:
    {{- if .Values.istio.enabled }}{{- include "bigbang.istioInjectionLabel" .  | nindent 4 }}{{- end }}
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}