{{- if and (or .Values.addons.jaeger.enabled) .Values.addons.jaeger.sso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tls-ca-sso
  namespace: jaeger
type: Opaque
data:
  ca.pem: {{ .Values.sso.certificate_authority | b64enc }}
{{- end }}