{{- if and  .Values.jaeger.enabled .Values.jaeger.sso.enabled .Values.sso.certificate_authority}}
apiVersion: v1
kind: Secret
metadata:
  name: tls-ca-sso
  namespace: jaeger
type: Opaque
data:
  ca.pem: {{ .Values.sso.certificate_authority | b64enc }}
{{- end }}