namespace: flux-system

resources:
  - gitrepository.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: bigbang-values
    behavior: create
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true