{{- if .Values.istio.enabled }}
{{- $fluxSettingsIstioCp := merge .Values.istio.flux .Values.flux -}}
{{- $name := include "bigbang.tagname" (merge .Values.istio (dict "name" "istio")) }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: istio
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: istio-system
  chart:
    spec:
      chart: {{ .Values.istio.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: {{ $name }}
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsIstioCp | nindent 2 }}

  {{- if .Values.istio.postRenderers }}
  postRenderers:
  {{ toYaml .Values.istio.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-{{ $name }}-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-{{ $name }}-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-{{ $name }}-values
      kind: Secret
      valuesKey: "overlays"

  dependsOn:
    - name: {{ include "bigbang.tagname" (merge .Values.istiooperator (dict "name" "istio-operator")) }}
      namespace: {{ .Release.Namespace }}

    {{- if .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
    {{- end }}
{{- end }}