{{- if .Values.istio.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.istio "name" "istio" "defaults" (include "bigbang.defaults.istio" .)) }}
{{- end }}

{{- define "bigbang.defaults.istio" -}}
hostname: {{ .Values.hostname }}

tracing:
  enabled:  {{ .Values.jaeger.enabled }}

imagePullSecrets:
  - private-registry

openshift: {{ .Values.openshift }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}

{{- if .Values.istio.ingressGateways }}
ingressGateways:
  istio-ingressgateway:
    enabled: false
{{- end }}

{{- range $name, $values := .Values.istio.ingressGateways }}
  {{ $name | nindent 2 }}:
    extraLabels:
      app.kubernetes.io/name: istio-controlplane
      app.kubernetes.io/component: "core"
      {{- include "commonLabels" $ | nindent 6}}
    k8s:
      service:
        type: {{ $values.type }}
        {{- if $values.nodePortBase }}
        ports: # Pulled from Istio gateway defaults (https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/values.yaml)
        # Ports default to "protocol: TCP" and "targetPort = port"
        # AWS ELB will by default perform health checks on the first port on this list. https://github.com/istio/istio/issues/12503
        - port: 15021
          name: status-port
          nodePort: {{ add $values.nodePortBase 0 }}
        - port: 80
          targetPort: 8080
          name: http2
          nodePort: {{ add $values.nodePortBase 1 }}
        - port: 443
          targetPort: 8443
          name: https
          nodePort: {{ add $values.nodePortBase 2 }}
        # SNI Routing port
        - port: 15443
          name: tls
          nodePort: {{ add $values.nodePortBase 3 }}
        {{- end }}
      serviceAnnotations:
        {{ $values.serviceAnnotations | default (dict) | toYaml | nindent 8 }}
{{- end }}

{{- if .Values.istio.gateways }}
gateways:
  main: null
{{- end }}
{{- range $name, $values := .Values.istio.gateways }}
  {{ $name | nindent 2 }}:
    selector:
      app: {{ $values.ingressGateway }}
    servers:
    - hosts:
      {{ tpl ($values.hosts | default (list) | toYaml) $ | nindent 8 }}
      port:
        name: https
        number: 8443
        protocol: HTTPS
      tls:
        credentialName: {{ $name }}-cert
        mode: {{ default "SIMPLE" $values.tls.mode }}
{{- end }}
{{- end }}