{{- if .Values.istio.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.istio "name" "istio" "defaults" (include "bigbang.defaults.istio" .)) }}
{{- end }}

{{- define "bigbang.defaults.istio" -}}
hostname: {{ .Values.hostname }}
sso:
  enabled: {{ .Values.istio.sso.enabled }}

imagePullSecrets:
  - private-registry

openshift: {{ .Values.openshift }}

{{- if .Values.istio.sso.enabled }}
ingress:
  kiali:
    service: authservice-haproxy-sso
    port: 8080
    namespace: authservice
  jaeger:
    service: authservice-haproxy-sso
    port: 8080
    namespace: authservice
{{- end }}

istio:
  kiali:
    hosts:
      - {{ .Values.istio.hostnames.kiali }}.{{ .Values.domain | default .Values.hostname }}

{{- if .Values.addons.keycloak.enabled }}
extraServers:
- port:
    name: https-keycloak
    protocol: TLS
    number: 8443
  hosts:
    - {{ .Values.addons.keycloak.hostnames.keycloak }}.{{ .Values.hostname }}
  tls:
    mode: PASSTHROUGH

hostnames:
  {{- range .Values }}
  {{- if kindIs "map" . }}
  {{- if .enabled }}
  {{- range .hostnames }}
  - {{ . }}.{{ $.Values.hostname }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}

{{- end -}}