{{- if and (not .Values.offline) (or .Values.logging.enabled .Values.clusterAuditor.enabled) }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: logging
  namespace: {{ .Release.Namespace }}
spec:
  ignore: |
    # exclude file extensions
    /**/*.md
    /**/*.txt
    /**/*.sh
  interval: {{ .Values.flux.interval }}
  ref:
{{- if .Values.logging.git.commit }}
    commit: {{ .Values.logging.git.commit }}
{{- else if .Values.logging.git.tag }}
    tag: {{ .Values.logging.git.tag }}
{{- else }}
    branch: {{ .Values.logging.git.branch }}
{{- end }}
  url: {{ .Values.logging.git.repo }}
{{- end }}
