{{- if .Values.logging.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logging-operator
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: logging
  chart:
    spec:
      chart: charts/logging-operator
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: logging
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  values:
    createCustomResource: false

  {{- if .Values.gatekeeper.enabled }}
  dependsOn:
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}