---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bigbang
spec:
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: bigbang
        namespace: bigbang
  interval: 5m0s
  valuesFrom:
    - name: bigbang-values
      kind: ConfigMap
      optional: true
    - name: bigbang-values
      kind: Secret
      optional: true