apiVersion: v1
kind: Secret
metadata:
    name: bigbang-secrets
    namespace: bigbang
data:
    values.yaml: ENC[AES256_GCM,data:BFDD4jq4c28INtaAjT+e9xkVhSplz38w3mzRPA8c+dL+IbU/oUQ/EqHXU3JqT+N9DpbbrwkzUoxTFWdEt1H08unoo+FO9MaART5Jl9sy50lzVfN5NYO8Jr3iC5xxeKLXZFiGHMnk9IQ=,iv:df+wJrOM/4eN5DbmFtyHt2ueOoVd0K7Bvrsn3v6o1Zk=,tag:N68lkNY3jGywqiMromsSTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-11-14T02:11:45Z'
    mac: ENC[AES256_GCM,data:MmkOGeeG1aRF7/Sh9oJmdz0AkBNaPw7wHsGf7fTEiH4L8DA8gQ6N9ahjkBoXZPIKFIeBy2DRiuoeC/7VLc+2WYrnqEIYcBTTnf+XweEMV+zQXWaQL1+H5QfeFWtym31LJHMHgBlH2NtKWUGcayVexItyivrkarinCIv0qvDX7p8=,iv:IOwI4lTN2iwPjpRHI2TfJcQFvZY3/aW3SHNMwO4qHlg=,tag:apK6uOh2exlyrZg5zuqWxA==,type:str]
    pgp:
    -   created_at: '2020-11-12T20:44:22Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA93W3Fi3CqSYARAAkynkQF477bTkJx7GtxQeuA7UYggpPf/y4SE4BeZ8t54f
            50epetpe2xYGSc3cKgeckU9VALKWWzvMe/JFkE9657H/mVgR3lFB7+5aaDsVnNcY
            vBgCc17EqnMcTri0B8QvA5D03vxT39ETVIBVV+aH47PgJ9kCTxD8OTkTGENe4R1u
            UzzR5IsxlWOxTN9ExdLrfVhhr4Q+jTs3bwl3mwry8lMQrpdFxmDPFmzXIWmynGlw
            /cMzfV9Y1P21sg4TS8Ag6lrjFsLPseKf4DsNv/kU4oqvQbYrAvZg+Znt6QvWMfc8
            UQKyojSKLtddkDAmt0g0vibvXZMglO14WWdXUlDtQcebUxwFs21OnPP2RfhRh+Ib
            o8p1lR61QtUSG3TdCY3PEp8K4Ss1nNWXUSdDHVUDlwLrqnJ866EFQ5+QiwF7hDFB
            3uc0lzz2bwJn60UbB6hZ9XSrtESlr+ETprxEwqUyq7+qrSP+xBJJUHA5gKkrPoho
            BCcyJvhjxZLutXjbM9/ab4l2Ove8wHMechP6MP3TXW4A8UW1YkynVSQuvreI3wGu
            RpLWMAeyPYDuLAzgWl+iJK/RMEPRIDliMpMpFlYI8fxkSCQ2rbTXDJX5/UB3Iq+7
            PVkL0sjIcAbH3jvljRrlcY5O2a7HlGz6GWo7wzM0yQCHD/D8nL99ui1mkK7GnoTS
            XgH+qWahhzeuEQZe06s4BKglls4wZYqH3H+cqcGC+b1u0PIt98SSCb0jpP3NsWcX
            zE2ExQj5WXmMwMqmqDhJUTwQ5oss1NmPGjo+lG7PU9CKsPgqMnDh5TBTebq5Lxc=
            =HUjd
            -----END PGP MESSAGE-----
        fp: 41BFF8BAF2586039F6293D835A2E820C25FE527C
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
