<<<<<<< HEAD
{{- if and (not .Values.offline) .Values.addons.vault.enabled }}
=======
{{- if and (not .Values.offline) .Values.vault.enabled }}
>>>>>>> b3d915d2 (add vault deployment)
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: vault
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: "sandbox"
    {{- include "commonLabels" . | nindent 4}}
spec:
  interval: {{ .Values.flux.interval }}
<<<<<<< HEAD
  url: {{ .Values.addons.vault.git.repo }}
  ref:
    {{- include "validRef" .Values.addons.vault.git | nindent 4 }}
=======
  url: {{ .Values.vault.git.repo }}
  ref:
    {{- include "validRef" .Values.vault.git | nindent 4 }}
>>>>>>> b3d915d2 (add vault deployment)
  {{ include "gitIgnore" . }}
  {{- include "gitCreds" . | nindent 2 }}
{{- end }}
