<<<<<<< HEAD
{{- if .Values.addons.vault.enabled }}
=======
{{- if .Values.vault.enabled }}
>>>>>>> b3d915d2 (add vault deployment)
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: "sandbox"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
<<<<<<< HEAD
{{- end }}
=======
{{- end }}
>>>>>>> b3d915d2 (add vault deployment)
