{{- if .Values.addons.vault.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.vault "name" "vault" "defaults" (include "bigbang.defaults.vault" .)) }}
{{- end }}

{{- define "bigbang.defaults.vault" -}}
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
{{- $domainName := default .Values.domain .Values.hostname }}
hostname: {{ $domainName }}
domain: {{ $domainName }}

openshift: {{ .Values.openshift }}

prometheus:
  servicemonitor:
    enabled: {{ .Values.monitoring.enabled }}

imagePullSecrets:
- name: private-registry



istio:
  enabled: {{ .Values.istio.enabled }}
  console:
    gateways:
    - istio-system/public
{{- end -}}
