{{- if .Values.addons.vault.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: "application-utilities"
    {{- include "commonLabels" . | nindent 4}}
spec:
  releaseName: vault
  targetNamespace: vault
  chart:
    spec:
      chart: {{ .Values.addons.vault.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: vault
        namespace: {{ .Release.Namespace }}


  {{- if .Values.addons.vault.postRenderers }}
  postRenderers:
  {{ toYaml .Values.addons.vault.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-vault-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-vault-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-vault-values
      kind: Secret
      valuesKey: "overlays"

  dependsOn:
    {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}

    {{- if and .Values.logging.enabled }}
    - name: ek
      namespace: {{ $.Release.Namespace }}
    {{- end }}
{{- end }}
