{{- if .Values.addons.coder.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: coder
    app.kubernetes.io/component: "developer"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: coder
  chart:
    spec:
      chart: {{ .Values.addons.coder.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: coder
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
  - name: values
    kind: Secret
    valuesKey: "coder.yaml"

  values:
    istio:
      enabled: {{ .Values.istio.enabled }}
    {{- if and .Values.addons.coder.database.host .Values.addons.coder.database.port .Values.addons.coder.database.username .Values.addons.coder.database.database .Values.addons.coder.database.password  }}
    postgres:
      useDefault: false
      host: {{ .Values.addons.coder.database.host }}
      port: {{ .Values.addons.coder.database.port }}
      user: {{ .Values.addons.coder.database.username }}
      database: {{ .Values.addons.coder.database.database }}
      passwordSecret: coder-postgres-secret
    {{- end }}
    global:
      imagePullSecrets:
      - name: private-registry
  dependsOn:
  {{- if .Values.istio.enabled }}
  - name: istio
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.monitoring.enabled }}
  - name: monitoring
    namespace: {{ .Release.Namespace }}
  {{- end }}
  
{{- end }}