{{- if .Values.addons.coder.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: coder
  labels:
    istio-injection: enabled
---
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: coder
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}
