{{- if .Values.addons.confluence.enabled }}
{{ $name := "confluence" }}
{{ $component := "collaboration-tools" }}
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/component: {{ $component }}
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
---
{{- if and .Values.addons.confluence.database.username .Values.addons.confluence.database.password (not .Values.addons.confluencedatabase.enabled) }}
{{ $namedb := "confluence-database" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $namedb }}
  namespace: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $namedb }}
    app.kubernetes.io/component: {{ $component }}
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/opaque
stringData:
  username: {{ .Values.addons.confluence.database.username | quote }}
  password: {{ .Values.addons.confluence.database.password | quote }}
{{- end }}
{{- end }}