{{- if .Values.addons.confluence.enabled }}
{{ $name := "confluence" }}
{{ $component := "collaboration-tools" }}
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/component: {{ $component }}
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
---
{{- if .Values.addons.confluence.database.host }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/component: {{ $component }}
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/opaque
stringData:
    postgresql-password: {{ .Values.addons.confluence.database.password }}
{{- end }}
{{- end }}