.k3d_before_script: &k3d_before_script
  # Starting dnsmasq for cluster dns resolution
  - docker run -d -p 53:53/udp -p 53:53 registry.dsop.io/platform-one/big-bang/pipeline-templates/pipeline-templates/go-dnsmasq:0eddd476
  - echo "nameserver 127.0.0.1" >> /etc/resolv.conf
  # Standup cluster
  - k3d cluster create --k3s-server-arg "--disable=traefik" --k3s-server-arg "--disable=metrics-server" -p 80:80@loadbalancer -p 443:443@loadbalancer --wait --agents $N_AGENTS --servers $N_SERVERS
  # Wait for core resources to become available
  - while ! (kubectl get node | grep -q "server"); do sleep 3; done
  - kubectl wait -n kube-system --for=condition=Ready $(kubectl get no -o name)
  - while ! (kubectl get po -n kube-system -o name | grep -q "pod/local-path-provisioner"); do sleep 3; done
  - while ! (kubectl get po -n kube-system -o name | grep -q "pod/local-coredns"); do sleep 3; done
  - kubectl wait -n kube-system --for=condition=Ready $(kubectl get no -o name)
  - kubectl wait -n kube-system --for=condition=Ready $(kubectl get po -o name -n kube-system)
  - kubectl get no; kubectl get po -A

.k3d_after_script: &k3d_after_script
  - k3d cluster delete --all

.k3d:
  image: registry.dsop.io/platform-one/big-bang/pipeline-templates/pipeline-templates/k3d-builder:045fb1c2
  services:
    - registry.dsop.io/platform-one/big-bang/pipeline-templates/pipeline-templates/docker:dind
  tags:
    - bigbang
    - privileged
    - public
  variables:
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    N_SERVERS: 1
    N_AGENTS: 0
  before_script:
    - *k3d_before_script
  after_script:
    - *k3d_after_script