apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bigbang
  labels:
    app.kubernetes.io/name: bigbang
spec:
  targetNamespace: bigbang
  interval: 10m
  chart:
    spec:
      chart: ./chart
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: bigbang
      #valuesFile: chart/values.yaml
  test: 
    {}
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 5
    cleanupOnFail: true
  rollback:
    timeout: 10m
  timeout: 10m
  valuesFrom:
    # Optional secret injected with https://repo1.dso.mil/platform-one/big-bang/terraform-modules/big-bang-terraform-launcher
    - kind: Secret
      name: terraform
      optional: true
    - kind: Secret
      name: common-bb
    - kind: ConfigMap
      name: common
    - kind: Secret
      name: environment-bb
    - kind: ConfigMap
      name: environment