apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: bigbang
spec:
  image: registry1.dsop.io/ironbank/elastic/elasticsearch/elasticsearch:7.9.2
  nodeSets:
  - name: master
    config:
      index.store.type: mmapfs
      node.data: false
      node.ingest: false
      node.master: true
      node.ml: false
      node.store.allow_mmap: true
      xpack.ml.enabled: false
      xpack.security.authc.token.enabled: true
    count: 1
    podTemplate:
      metadata:
        annotations:
          fluentbit.io/exclude-istio-proxy: "true"
          prometheus.istio.io/merge-metrics: "false"
          #        spec:
          #          automountServiceAccountToken: true
          #          containers:
          #            - name: elasticsearch
          #              env:
          #                - name: ES_JAVA_OPTS
          #                  value: "-Xms1g -Xmx1g"
          #              resources:
          #                requests:
          #                  memory: 2Gi
          #                  cpu: 0.5
          #                limits:
          #                  memory: 3Gi
          #                  cpu: 2

          sidecar.istio.io/rewriteAppHTTPProbers: "true"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
      spec:
        automountServiceAccountToken: true
  - name: data
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        resources:
          requests:
            storage: 10Gi
        accessModes:
        - ReadWriteOnce
    config:
      index.store.type: mmapfs
      node.data: true
      node.ingest: true
      node.master: false
      node.ml: false
      node.store.allow_mmap: true
      xpack.ml.enabled: false
      xpack.security.authc.token.enabled: true
    count: 1
    podTemplate:
      metadata:
        annotations:
          fluentbit.io/exclude-istio-proxy: "true"
          prometheus.istio.io/merge-metrics: "false"
          sidecar.istio.io/rewriteAppHTTPProbers: "true"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
      spec:
        automountServiceAccountToken: true
        #          containers:
        #            - name: elasticsearch
        #              env:
        #                - name: ES_JAVA_OPTS
        #                  value: "-Xms1g -Xmx1g"
        #              resources:
        #                requests:
        #                  memory: 2Gi
        #                  cpu: 0.5
        #                limits:
        #                  memory: 3Gi
        #                  cpu: 2
  version: 7.9.2
