{{- if .Values.clusterAuditor.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-auditor-policies
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: cluster-auditor
  chart:
    spec:
      chart: {{ .Values.clusterAuditor.git.path }}/policies
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: cluster-auditor
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
  - name: values
    kind: Secret
    valuesKey: "clusterauditor.yaml"

  {{- if .Values.gatekeeper.enabled }}
  dependsOn:
  - name: gatekeeper
    namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}