{{- if .Values.gatekeeper.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-auditor
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: cluster-auditor
  chart:
    spec:
      chart: charts/application
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: cluster-auditor
        namespace: {{ .Release.Namespace }}
  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  values:
    #conversion from umbrella values to package values
    image:
      repository: registry1.dsop.io/ironbank/opensource/openpolicyagent/gatekeeper
      release: v3.1.2
    disableValidatingWebhook: true
    createNamespace: false
    {{- if and (ne .Values.registryCredentials.username "") (ne .Values.registryCredentials.password "") }}
    imagePullSecrets: [ private-registry ]
    {{- end }}
  valuesFrom:
  - name: values
    kind: Secret
    valuesKey: "clusterauditor.yaml"
  {{- if .Values.certmanager.enabled }}
  dependsOn:
  - name: gatekeeper
    namespace: {{ .Release.Namespace }}
  - name: eck-operator
    namespace: {{ .Release.Namespace }}
  - name: cluster-auditor-policies
    namespace: {{ .Release.Namespace}}
  {{- end }}
{{- end }}