---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: cluster-auditor
    app.kubernetes.io/component: "core"
  name: kube-api-server
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 443
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    pp.kubernetes.io/name: cluster-auditor
    app.kubernetes.io/component: "core"
  name: es-communication
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 9200
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/component: "core"
  name: deny-ingress
  namespace: flux-system
spec:
  egress:
  - {}
  ingress:
  - from:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---