{{- if and .Values.logging.enabled .Values.loki.enabled (eq .Values.logging.engine "plg") }}
{{- include "values-secret" (dict "root" $ "package" .Values.loki "name" "loki" "defaults" (include "bigbang.defaults.loki" .)) }}
{{- end }}

{{- define "bigbang.defaults.loki" -}}
hostname: {{ .Values.hostname }}

openshift: {{ .Values.openshift }}

istio:
  enabled: {{ .Values.istio.enabled }}

imagePullSecrets:
  - name: private-registry
{{- end -}}
