{{- if and .Values.logging.enabled .Values.loki.enabled (eq .Values.logging.engine "plg") }}
{{- include "values-secret" (dict "root" $ "package" .Values.logging "name" "loki" "defaults" (include "bigbang.defaults.logging" .)) }}
{{- end }}

{{- define "bigbang.defaults.logging" -}}
hostname: {{ .Values.hostname }}

openshift: {{ .Values.openshift }}

istio:
  enabled: {{ .Values.istio.enabled }}

loki:
  imagePullSecrets:
    - name: private-registry
{{- end -}}
