  
{{- if .Values.addons.minio.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: mattermost-operator
  labels:
    istio-injection: enabled
---
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: mattermost-operator
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
---
