{{- if .Values.addons.minio.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    istio-injection: enabled
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: "application-utilities"
    {{- include "commonLabels" . | nindent 4}}
---
{{- if (   include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: minio
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
---
# probably want to get rid of this eventually
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
  namespace: minio
type: Opaque
data:
  accesskey: bWluaW8= # base 64 encoded "minio" (echo -n 'minio' | base64)
  secretkey: bWluaW8xMjM= # based 64 encoded "minio123" (echo -n 'minio123' | base64)
{{- end }}