{{- if .Values.addons.minio.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    {{- if .Values.istio.enabled }}{{- include "bigbang.istioInjectionLabel" .  | nindent 4 }}{{- end }}
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: "application-utilities"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}
