{{- if .Values.addons.minio.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.minio "name" "minio" "defaults" (include "bigbang.defaults.minio" .)) }}
{{- end }}

{{- define "bigbang.defaults.minio" -}}
hostname: {{ .Values.hostname }}

istio:
  enabled: {{ .Values.istio.enabled }}

minioRootCreds: minio-root-creds-secret

monitoring:
  enabled: {{ .Values.monitoring.enabled }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

podAnnotations:
  sidecar.istio.io/inject: "true"
  traffic.sidecar.istio.io/includeInboundPorts: "*"
  traffic.sidecar.istio.io/excludeInboundPorts: "9443"

tenants:
  imagePullSecret:
    name: private-registry
  secrets:
    accessKey: {{ .Values.addons.minio.accesskey | default "minio" }}
    secretKey: {{ .Values.addons.minio.secretkey | default "minio123" }}


{{- end -}}
