{{- if .Values.addons.minio.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.minio "name" "minio" "defaults" (include "bigbang.defaults.minio" .)) }}
{{- end }}

{{- define "bigbang.defaults.minio" -}}
hostname: {{ .Values.hostname }}

istio:
  enabled: {{ .Values.istio.enabled }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}

podAnnotations:
  sidecar.istio.io/inject: "true"
  traffic.sidecar.istio.io/includeInboundPorts: "*"
  traffic.sidecar.istio.io/excludeInboundPorts: "9443"

imagePullSecrets:
  - name: private-registry

tenants:
  secrets:
    name: minio-creds-secret
    accessKey: {{ .Values.addons.minio.accesskey | default "minio" }}
    secretKey: {{ .Values.addons.minio.secretkey | default "minio123" }}
  imagePullSecret:
    name: private-registry

{{- end -}}
